/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ParkirGUI;
import Kendaraan.*;
import javax.swing.JOptionPane;
import DataStructure.*;
import Waktu.Waktu;
import java.text.SimpleDateFormat;

/**
 *
 * @author Windows 10
 */
public class EditMenu extends javax.swing.JFrame {

    /**
     * Creates new form CreateMenu
     */
    private LinkedList list;
    private ElementList hCari;
    public EditMenu(LinkedList list) {
        this.list = list;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        timePicker1 = new com.raven.swing.TimePicker();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        platField = new javax.swing.JTextField();
        masukPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jmasukField = new javax.swing.JTextField();
        waktuDatangAutoButton = new javax.swing.JButton();
        keluarPanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jkeluarField = new javax.swing.JTextField();
        waktuKeluarAutoButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        readMenuButton = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel1.setText("Parkir Kendaraan");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Data"));

        jLabel4.setText("Plat Nomor                       :");

        platField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platFieldActionPerformed(evt);
            }
        });

        masukPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Waktu Masuk"));

        jLabel5.setText("Waktu  :");

        jmasukField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmasukFieldActionPerformed(evt);
            }
        });

        waktuDatangAutoButton.setText("Dapatkan Waktu Sekarang");
        waktuDatangAutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuDatangAutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout masukPanelLayout = new javax.swing.GroupLayout(masukPanel);
        masukPanel.setLayout(masukPanelLayout);
        masukPanelLayout.setHorizontalGroup(
            masukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masukPanelLayout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jmasukField)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, masukPanelLayout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addComponent(waktuDatangAutoButton)
                .addGap(19, 19, 19))
        );
        masukPanelLayout.setVerticalGroup(
            masukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(masukPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jmasukField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(waktuDatangAutoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        keluarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Waktu Keluar"));

        jLabel8.setText("Waktu   :");

        jkeluarField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jkeluarFieldActionPerformed(evt);
            }
        });

        waktuKeluarAutoButton.setText("Dapatkan Waktu Sekarang");
        waktuKeluarAutoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuKeluarAutoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout keluarPanelLayout = new javax.swing.GroupLayout(keluarPanel);
        keluarPanel.setLayout(keluarPanelLayout);
        keluarPanelLayout.setHorizontalGroup(
            keluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarPanelLayout.createSequentialGroup()
                .addGroup(keluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(keluarPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jkeluarField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keluarPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(waktuKeluarAutoButton)))
                .addContainerGap())
        );
        keluarPanelLayout.setVerticalGroup(
            keluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(keluarPanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(keluarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jkeluarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104)
                .addComponent(waktuKeluarAutoButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(masukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(keluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(platField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(platField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masukPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keluarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        editButton.setText("Edit Data");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        backButton.setText("Kembali Ke Menu");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        readMenuButton.setText("Lihat Semua Data");
        readMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editButton)
                    .addComponent(backButton)
                    .addComponent(readMenuButton))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void platFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platFieldActionPerformed

    private void jmasukFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmasukFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmasukFieldActionPerformed

    private void jkeluarFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jkeluarFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jkeluarFieldActionPerformed
    
    public void setPlatText(String plat){
        platField.setText(plat);
        platField.setEditable(false);
        this.cariData();
    
    }
    public void hideAll(){
        masukPanel.setVisible(false);
        keluarPanel.setVisible(false);
        editButton.setVisible(false);
    }
    
    public void showAll(){
        masukPanel.setVisible(true);
        keluarPanel.setVisible(true);
        editButton.setVisible(true);
    }
    
    
    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        this.editData();
    }//GEN-LAST:event_editButtonActionPerformed
 private void backToMain(){
        MainMenu obj = new MainMenu(this.list);
        obj.setVisible(true);
        dispose();
    }
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        backToMain();
    }//GEN-LAST:event_backButtonActionPerformed
    private void setTimeStampNowForDatang(){
         String timeStamp = new SimpleDateFormat("HH:mm:ss").format(new java.util.Date());
         jmasukField.setText(timeStamp);
    }
    private void setTimeStampNowForKeluar(){
        String timeStamp = new SimpleDateFormat("HH:mm:ss").format(new java.util.Date());
       jkeluarField.setText(timeStamp);
    }
    private void waktuKeluarAutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuKeluarAutoButtonActionPerformed
       this.setTimeStampNowForKeluar();
    }//GEN-LAST:event_waktuKeluarAutoButtonActionPerformed
    
    private void cariData(){
     this.hCari=this.list.search(platField.getText());
    if(hCari==null){
        JOptionPane.showMessageDialog(null, "Data Tidak berhasi ditemukan ! ", "Error", 1);
//        this.hideAll();
    }
    
    
    else{
                JOptionPane.showMessageDialog(null, "Data berhasi ditemukan ! ", "Sukses", 1);
//                this.showAll();
                jmasukField.setText(this.hCari.getData().getWaktudatang().getWaktu());
                jkeluarField.setText(this.hCari.getData().getWaktuPulang().getWaktu());

    
    }
    
    }
    
    private void editData(){
        this.list.editData(jmasukField.getText(), jkeluarField.getText(), hCari);
        JOptionPane.showMessageDialog(null, "Data Berhasil Di ubah !  ", "Sukses", 1);

    }
    private void waktuDatangAutoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuDatangAutoButtonActionPerformed
        this.setTimeStampNowForDatang();
    }//GEN-LAST:event_waktuDatangAutoButtonActionPerformed
 private void changeToReadMenu(){
        ReadMenu obj = new ReadMenu(this.list);
        obj.showTable();
        obj.setVisible(true);  
        dispose(); 
        
    }
    private void readMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMenuButtonActionPerformed
        this.changeToReadMenu();
    }//GEN-LAST:event_readMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jkeluarField;
    private javax.swing.JTextField jmasukField;
    private javax.swing.JPanel keluarPanel;
    private javax.swing.JPanel masukPanel;
    private javax.swing.JTextField platField;
    private javax.swing.JButton readMenuButton;
    private com.raven.swing.TimePicker timePicker1;
    private javax.swing.JButton waktuDatangAutoButton;
    private javax.swing.JButton waktuKeluarAutoButton;
    // End of variables declaration//GEN-END:variables
}
