/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.aja;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;

public class App extends Application{
    
    @Override
    public void start(Stage primaryStage) throws Exception{
        // FXMLLoader fxmlLoader = new FXMLLoader(getClass().getClassLoader().getResource("Java.fxml"));
        // fxmlLoader.setRoot(new AnchorPane()); // set root misal pake anchor pane, grid pane dll
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/InGame.fxml"));; 

        Scene scene = new Scene(root);

        primaryStage.setTitle("TIC TAC TOE");
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}
