/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.javagui2;

/**
 *
 * @author prame
 */
public class JavaGUI2 extends javax.swing.JFrame {

    /**
     * Creates new form JavaGUI2
     */
    public JavaGUI2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        lblProdi = new javax.swing.JLabel();
        lblAngkatan = new javax.swing.JLabel();
        lblNoUrut = new javax.swing.JLabel();
        fldProdi = new javax.swing.JComboBox<>();
        rb2019 = new javax.swing.JRadioButton();
        rb2020 = new javax.swing.JRadioButton();
        rb2021 = new javax.swing.JRadioButton();
        rb2022 = new javax.swing.JRadioButton();
        fldNoUrut = new javax.swing.JTextField();
        btnProses = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblHasilNPM = new javax.swing.JLabel();
        lblOutputNPM = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        lblJudul = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblProdi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblProdi.setText("Prodi           :");
        lblProdi.setPreferredSize(new java.awt.Dimension(100, 20));

        lblAngkatan.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblAngkatan.setText("Angkatan     :");
        lblAngkatan.setPreferredSize(new java.awt.Dimension(100, 20));

        lblNoUrut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblNoUrut.setText("No Urut       :");
        lblNoUrut.setPreferredSize(new java.awt.Dimension(100, 20));

        fldProdi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        fldProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematika", "Kimia", "Fisika", "Biologi", "Statistika", "Geofisika", "Teknik Informatika", "Teknik Elektro", "Aktuaria", "Teknologi Industri Kimia" }));
        fldProdi.setToolTipText("");
        fldProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldProdiActionPerformed(evt);
            }
        });

        rb2019.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2019.setText("2019");
        rb2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2019ActionPerformed(evt);
            }
        });

        rb2020.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2020.setText("2020");
        rb2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2020ActionPerformed(evt);
            }
        });

        rb2021.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2021.setText("2021");
        rb2021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2021ActionPerformed(evt);
            }
        });

        rb2022.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        rb2022.setText("2022");
        rb2022.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2022ActionPerformed(evt);
            }
        });

        fldNoUrut.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N

        btnProses.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnProses.setText("Proses");
        btnProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProsesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(fldProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fldNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2019, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2020, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2021, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rb2022, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAngkatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb2019))
                .addGap(18, 18, 18)
                .addComponent(rb2020)
                .addGap(18, 18, 18)
                .addComponent(rb2021)
                .addGap(18, 18, 18)
                .addComponent(rb2022)
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fldNoUrut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(btnProses)
                .addGap(22, 22, 22))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblHasilNPM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblHasilNPM.setText("Hasil NPM anda adalah: ");

        lblOutputNPM.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblOutputNPM.setText(" ");

        btnSelesai.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnSelesai.setText("Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSelesai)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblHasilNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblOutputNPM, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHasilNPM)
                    .addComponent(lblOutputNPM))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSelesai)
                .addGap(24, 24, 24))
        );

        lblJudul.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblJudul.setText("Proses Pembentukan NPM");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblJudul)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldProdiActionPerformed

    private void rb2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2019ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2019ActionPerformed

    private void rb2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2020ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2020ActionPerformed

    private void rb2021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2021ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2021ActionPerformed

    private void rb2022ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2022ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2022ActionPerformed

    private void btnProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProsesActionPerformed
        String prodi = null;
        String angkatan= null;
        
        //Conditional Statement untuk pilihan prodi melalui ComboBox
        if (fldProdi.getSelectedIndex() == 0) {
            prodi = "01";
        }
        else if (fldProdi.getSelectedIndex() == 1) {
            prodi = "02";
        }
        else if (fldProdi.getSelectedIndex() == 2) {
            prodi = "03";
        }
        else if (fldProdi.getSelectedIndex() == 3) {
            prodi = "04";
        }
        else if (fldProdi.getSelectedIndex() == 4) {
            prodi = "06";
        }
        else if (fldProdi.getSelectedIndex() == 5) {
            prodi = "07";
        }
        else if (fldProdi.getSelectedIndex() == 6) {
            prodi = "08";
        }
        else if (fldProdi.getSelectedIndex() == 7) {
            prodi = "09";
        }
        else if (fldProdi.getSelectedIndex() == 8) {
            prodi = "10";
        }
        else if (fldProdi.getSelectedIndex() == 9) {
            prodi = "11";
        }
        
        //Conditional Statement untuk pilihan angkatan melalui Radio Button
        if (rb2019.isSelected()){
            angkatan = "19";
        } 
        else if (rb2020.isSelected()){
            angkatan = "20";
        }
        else if (rb2021.isSelected()){
            angkatan = "21";
        }
        else if (rb2022.isSelected()){
            angkatan = "22";
        }
        lblOutputNPM.setText("14" + prodi + "10"+ angkatan + fldNoUrut.getText());
    }//GEN-LAST:event_btnProsesActionPerformed

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSelesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaGUI2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaGUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProses;
    private javax.swing.JButton btnSelesai;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fldNoUrut;
    private javax.swing.JComboBox<String> fldProdi;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAngkatan;
    private javax.swing.JLabel lblHasilNPM;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNoUrut;
    private javax.swing.JLabel lblOutputNPM;
    private javax.swing.JLabel lblProdi;
    private javax.swing.JRadioButton rb2019;
    private javax.swing.JRadioButton rb2020;
    private javax.swing.JRadioButton rb2021;
    private javax.swing.JRadioButton rb2022;
    // End of variables declaration//GEN-END:variables
}
